on:
  pull_request:
  push:
    branches: main

name: CI Jobs

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          # Can't set working-directory for some reason https://github.com/actions-rs/cargo/issues/86
          args: --manifest-path ./rs/Cargo.toml

  test-node:
    name: Test Suite (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run tests
        working-directory: ./rs
        run: wasm-pack test --node

  test-browser:
    name: Test Suite (Browser)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test GeckoDriver
        working-directory: ./rs
        run: wasm-pack test --firefox --headless -- --features browser_test

      - name: Test ChromeDriver
        working-directory: ./rs
        run: wasm-pack test --chrome --headless -- --features browser_test
