export const HORIZONTAL_TICKER_PADDING = 0; // 64
export const WAVEFORM_BASE_SAMPLES_PER_PIXEL = 32;
export const ZOOM_FAC = 17 / 16;
export const TICKER_PIXEL_SPACING = 300;
export const SPECTROGRAM_CHUNK_SIZE = 4096;
