on:
  pull_request:
  push:
    branches: main

name: CI Jobs

jobs:
  check-rust:
    name: Check Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          # Can't set working-directory for some reason https://github.com/actions-rs/cargo/issues/86
          args: --manifest-path ./rs/Cargo.toml

      - name: Install dependencies
        run: pnpm install

      - name: Run svelte check
        run: pnpm check

      - name: Check linting
        run: pnpm lint

  check-svelte:
    name: Check Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run svelte check
        run: pnpm check

      - name: Check linting
        run: pnpm lint
